# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Deploy Tag
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: The version number of the release

concurrency: WordPress.org

permissions:
  attestations: write
  contents: read
  id-token: write
  issues: write

jobs:
  deploy:
    name: Deploy Tag
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-deploy-tag.yml@attestation
    with:
      deploy: ${{ github.event_name != 'workflow_dispatch' }}
      plugin: query-monitor
      readme: readme.txt
      version: ${{ github.event_name != 'workflow_dispatch' && github.event.release.tag_name || github.event.inputs.version }}
    secrets:
      WPORG_SVN_USERNAME: ${{ secrets.WPORG_SVN_USERNAME }}
      WPORG_SVN_PASSWORD: ${{ secrets.WPORG_SVN_PASSWORD }}
  attest:
    name: Attest release
    runs-on: ubuntu-latest
    timeout-minutes: 70
    needs: deploy
    steps:
      - name: Perform attestation
        uses: johnbillion/plugin-infrastructure/@attestation
        with:
          attest: ${{ github.event_name != 'workflow_dispatch' }}
          plugin: query-monitor
          version: ${{ needs.deploy.outputs.version }}
          zip-path: ${{ needs.deploy.outputs.zip-path }}
